[tool.ruff.lint]
select = ["E", "F"]
ignore = ["F401"]
fixable = ["ALL"]
extend-safe-fixes = ["E501"]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint.flake8-tidy-imports]
# Disallow all relative imports.
ban-relative-imports = "all"